## Installing Dependencies

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import re

In [2]:
pd.set_option('display.max_rows', None)

## Loading Data

In [3]:
raw_data = pd.read_csv('../data/raw_data.csv')
raw_data.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [4]:
raw_data.shape

(4009, 12)

In [5]:
raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   str
 1   model         4009 non-null   str
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   str
 4   fuel_type     3839 non-null   str
 5   engine        4009 non-null   str
 6   transmission  4009 non-null   str
 7   ext_col       4009 non-null   str
 8   int_col       4009 non-null   str
 9   accident      3896 non-null   str
 10  clean_title   3413 non-null   str
 11  price         4009 non-null   str
dtypes: int64(1), str(11)
memory usage: 376.0 KB

## Data Cleaning & Prepraration

In [6]:
data = raw_data.copy()

### Convert To Numerical Datatype

**To Do**:
- Milage
- Price

In [7]:
data.milage = raw_data.milage.str.split(' ').str[0].str.replace(',', '').astype(float)

In [8]:
data.price = data.price.str.replace({'$': '', ',': ''}).astype(float)

### Convert To NaN

In [9]:
data.isna().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

**To do:**
- fuel_type
- accident
- clean_title

In [10]:
data.fuel_type.value_counts()

fuel_type
Gasoline          3309
Hybrid             194
E85 Flex Fuel      139
Diesel             116
–                   45
Plug-In Hybrid      34
not supported        2
Name: count, dtype: int64

#### Fuel_Type

In [11]:
data.fuel_type = data['fuel_type'].replace('–', np.nan)

In [12]:
data.fuel_type.value_counts()

fuel_type
Gasoline          3309
Hybrid             194
E85 Flex Fuel      139
Diesel             116
Plug-In Hybrid      34
not supported        2
Name: count, dtype: int64

#### Accident

In [13]:
data.accident.value_counts()

accident
None reported                             2910
At least 1 accident or damage reported     986
Name: count, dtype: int64

In [14]:
data.accident = data.accident.replace('None reported', np.nan)

In [15]:
data.accident.value_counts()

accident
At least 1 accident or damage reported    986
Name: count, dtype: int64

#### Clean_Title

In [16]:
data.clean_title.value_counts()

clean_title
Yes    3413
Name: count, dtype: int64

In [17]:
data.brand = data.brand.str.title()

In [18]:
data.brand.unique()

<StringArray>
[         'Ford',       'Hyundai',         'Lexus',      'Infiniti',
          'Audi',         'Acura',           'Bmw',         'Tesla',
          'Land',         'Aston',        'Toyota',       'Lincoln',
        'Jaguar', 'Mercedes-Benz',         'Dodge',        'Nissan',
       'Genesis',     'Chevrolet',           'Kia',          'Jeep',
       'Bentley',         'Honda',         'Lucid',          'Mini',
       'Porsche',        'Hummer',      'Chrysler',         'Volvo',
      'Cadillac',   'Lamborghini',      'Maserati',    'Volkswagen',
        'Subaru',        'Rivian',           'Gmc',           'Ram',
          'Alfa',       'Ferrari',         'Scion',    'Mitsubishi',
         'Mazda',        'Saturn',       'Bugatti',      'Polestar',
   'Rolls-Royce',       'Mclaren',         'Buick',         'Lotus',
       'Pontiac',          'Fiat',         'Karma',          'Saab',
       'Mercury',      'Plymouth',         'Smart',       'Maybach',
        'Suzuki']
Length: 57, dtype: str

In [19]:
data.columns

Index(['brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title',
       'price'],
      dtype='str')

### Extracting Important Categories

**To do:**
- engine column
    - Hourse Power
    - Engine Size
    - Number of Cylinders
- transmission column

#### Engine

In [20]:
data.engine.head(20)

0     300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...
1                                  3.8L V6 24V GDI DOHC
2                                        3.5 Liter DOHC
3     354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...
4                            2.0L I4 16V GDI DOHC Turbo
5                                             2.4 Liter
6          292.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
7          282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel
8         311.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
9           534.0HP Electric Motor Electric Fuel System
10                                                   V6
11        715.0HP 5.2L 12 Cylinder Engine Gasoline Fuel
12    382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...
13        400.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
14                               2.0 Liter Supercharged
15         375.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
16                           2.0L I4 16V GDI DOHC Turbo
17        305.0HP 3.6L V6 Cylinder Engine Gasoline Fuel
18        287.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
19         550.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
Name: engine, dtype: str

In [21]:
data['HP'] = data['engine'].str.extract(r'(\d+\.\d+)HP')

In [22]:
data.HP.head()

0    300.0
1      NaN
2      NaN
3    354.0
4      NaN
Name: HP, dtype: str

In [23]:
data['engine_size'] = data.engine.str.extract(r'(\d+\.\d+)(?:\sLiter|L)')

In [24]:
data.engine_size.head(20)

0     3.7
1     3.8
2     3.5
3     3.5
4     2.0
5     2.4
6     2.0
7     4.4
8     3.5
9     NaN
10    NaN
11    5.2
12    3.0
13    3.0
14    2.0
15    5.0
16    2.0
17    3.6
18    3.5
19    5.0
Name: engine_size, dtype: str

In [25]:
cylider_filter = data.engine.str.extract(r'(\d+)V|V(\d+)|(\d+) Cylinder').replace(np.nan, 0).astype(int)
data['n_cylinders'] = cylider_filter[0] + cylider_filter[1] + cylider_filter[2]
data['n_cylinders'] = data.n_cylinders.replace(0, np.nan)

In [26]:
data.n_cylinders.head(20)

0      6.0
1      6.0
2      NaN
3      6.0
4     16.0
5      NaN
6      4.0
7      8.0
8      6.0
9      NaN
10     6.0
11    12.0
12     6.0
13     6.0
14     NaN
15     8.0
16    16.0
17     6.0
18     6.0
19     8.0
Name: n_cylinders, dtype: float64

#### Transmission

In [27]:
data.transmission.head(20)

0                        6-Speed A/T
1                  8-Speed Automatic
2                          Automatic
3                        7-Speed A/T
4                  8-Speed Automatic
5                                  F
6                        6-Speed A/T
7                                A/T
8                        6-Speed A/T
9                                A/T
10                         Automatic
11                       8-Speed A/T
12                               A/T
13    Transmission w/Dual Shift Mode
14                         Automatic
15                               A/T
16                 9-Speed Automatic
17                               A/T
18                       6-Speed M/T
19                       8-Speed A/T
Name: transmission, dtype: str

In [28]:
data.transmission.value_counts()

transmission
A/T                                                                 1037
8-Speed A/T                                                          406
Transmission w/Dual Shift Mode                                       398
6-Speed A/T                                                          362
6-Speed M/T                                                          248
Automatic                                                            237
7-Speed A/T                                                          209
8-Speed Automatic                                                    176
10-Speed A/T                                                         119
5-Speed A/T                                                           86
9-Speed A/T                                                           74
6-Speed Automatic                                                     73
4-Speed A/T                                                           72
1-Speed A/T                                                           64
CVT Transmission                                                      62
5-Speed M/T                                                           59
10-Speed Automatic                                                    56
9-Speed Automatic                                                     47
M/T                                                                   40
Automatic CVT                                                         37
7-Speed Automatic with Auto-Shift                                     24
1-Speed Automatic                                                     14
7-Speed M/T                                                           10
8-Speed Automatic with Auto-Shift                                      9
5-Speed Automatic                                                      9
6-Speed Manual                                                         8
Transmission Overdrive Switch                                          7
7-Speed Automatic                                                      7
6-Speed Automatic with Auto-Shift                                      5
4-Speed Automatic                                                      4
Variable                                                               4
Automatic, 8-Spd                                                       4
–                                                                      4
2                                                                      3
2-Speed A/T                                                            3
F                                                                      2
Manual                                                                 2
7-Speed Manual                                                         2
Automatic, 9-Spd 9G-Tronic                                             2
Manual, 6-Spd                                                          2
CVT-F                                                                  1
8-SPEED AT                                                             1
Automatic, 8-Spd Sport w/Sport & Manual Modes                          1
Auto, 6-Spd w/CmdShft                                                  1
Automatic, 8-Spd PDK Dual-Clutch                                       1
Automatic, 8-Spd M STEPTRONIC w/Drivelogic, Sport & Manual Modes       1
Automatic, 8-Spd Dual-Clutch                                           1
6-Speed                                                                1
Single-Speed Fixed Gear                                                1
Automatic, 10-Spd                                                      1
2-Speed Automatic                                                      1
7-Speed                                                                1
Automatic, 7-Spd S tronic Dual-Clutch                                  1
6-Speed Electronically Controlled Automatic with O                     1
6 Speed At/Mt                                                          1
8-SPEED A/T                                                            1
10-Speed Automatic with Overdrive                                      1
7-Speed DCT Automatic                                                  1
9-Speed Automatic with Auto-Shift                                      1
SCHEDULED FOR OR IN PRODUCTION                                         1
6 Speed Mt                                                             1
8-Speed Manual                                                         1
Name: count, dtype: int64

In [29]:
data[data.transmission == 'F']

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,HP,engine_size,n_cylinders
5,Acura,ILX 2.4L,2016,136397.0,Gasoline,2.4 Liter,F,Silver,Ebony.,NaN,NaN,14798.0,NaN,2.4,NaN
476,Acura,MDX w/Technology Package,2023,3415.0,Gasoline,3.5 Liter SOHC,F,White,Parchment.,NaN,NaN,54998.0,NaN,3.5,NaN

In [30]:
data.transmission = data.transmission.replace('F', np.nan)

After Investigating Unique Values

In [31]:
def transmission_mapping(x):

    if pd.isna(x):
        return np.nan

    x = str(x)

    if x in ['Transmission Overdrive Switch',
            '–',
            '2',
            '6-Speed',
            'Single-Speed Fixed Gear',
            '7-Speed',
            'SCHEDULED FOR OR IN PRODUCTION']:
        return np.nan


    elif x in ['Transmission w/Dual Shift Mode']:
        return 'Dual Clutch'


    elif x in ['Variable', 'CVT']:
        return 'CVT'


    elif 'AT/MT' in x:
        return 'Automatic'


    elif any(word in x for word in ['A/T',
                                    'AT',
                                    'Automatic',
                                    'Auto']):
        return 'Automatic'


    elif any(word in x for word in ['M/T',
                                    'MT',
                                    'Manual']):
        return 'Manual'


    return np.nan

In [32]:
data.transmission = data.transmission.apply(transmission_mapping)

In [33]:
data.transmission.value_counts()

transmission
Automatic      3150
Dual Clutch     398
Manual          372
CVT               4
Name: count, dtype: int64

In [34]:
data.to_csv("../data/clean_data.csv", index=False)